#!/usr/bin/env bash
# sends a file to a remote server
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file FILE_PATH SERVER_IP USER_NAME SSH_KEY_PATH"
    exit 1
fi
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
