#!/usr/bin/env bash
# Refresh package information
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Start the Nginx service
sudo service nginx start

# Ensure Nginx starts automatically on system boot
sudo systemctl enable nginx

# Set up a custom HTML file
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

# Reload Nginx to apply changes
sudo service nginx restart

# Permit HTTP traffic through the firewall (if UFW is in use)
sudo ufw allow 'Nginx Full'
